"""add name capabilities assistant_profiles

Revision ID: c50a85e97075
Revises: ab414e9ea80c
Create Date: 2024-12-12 17:08:31.636091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c50a85e97075'
down_revision: Union[str, None] = 'ab414e9ea80c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistant_profiles', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('assistant_profiles', sa.Column('capabilities', sa.ARRAY(sa.String(length=255)), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistant_profiles', 'capabilities')
    op.drop_column('assistant_profiles', 'name')
    # ### end Alembic commands ###
