"""add instructions in email thread

Revision ID: cf0b62c5f377
Revises: c50a85e97075
Create Date: 2024-12-13 00:27:50.319346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf0b62c5f377'
down_revision: Union[str, None] = 'c50a85e97075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_threads', sa.Column('instructions', sa.String(length=1000), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('email_threads', 'instructions')
    # ### end Alembic commands ###
