"""Create email threads table

Revision ID: 66ca079fc6c0
Revises: 9cbf2dc292d9
Create Date: 2024-10-27 18:47:59.377618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66ca079fc6c0'
down_revision: Union[str, None] = '9cbf2dc292d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Удаляем enum тип если он существует
    op.execute('DROP TYPE IF EXISTS threadstatus')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('thread_name', sa.String(), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', name='threadstatus'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_threads_id'), 'email_threads', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_threads_id'), table_name='email_threads')
    op.drop_table('email_threads')
    op.execute('DROP TYPE IF EXISTS threadstatus')
    # ### end Alembic commands ###
